# Generated by Django 2.2.7 on 2019-11-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='roadmap.RoadmapParent', verbose_name='親ロードマップ'),
        ),
    ]
