# Generated by Django 2.2.7 on 2019-11-12 05:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('detail', models.CharField(default='', max_length=200, verbose_name='詳細')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_id', models.UUIDField(default='', null=True)),
            ],
            options={
                'db_table': 'roadmap',
            },
        ),
    ]
