# Generated by Django 2.2.7 on 2019-11-13 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='next_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
